<?php /* Smarty version Smarty-3.1.14, created on 2020-12-21 08:38:00
         compiled from "/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/list-thumbs.html" */ ?>
<?php /*%%SmartyHeaderCode:7800121335fe034b8055592-72417469%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '12d5c1930d27634d9d8eec999a53715c3b2440df' => 
    array (
      0 => '/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/list-thumbs.html',
      1 => 1596613227,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '7800121335fe034b8055592-72417469',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'category' => 0,
    'theme_settings' => 0,
    'show_features' => 0,
    '_products_list_features_limit' => 0,
    'products' => 0,
    'wa' => 0,
    '_products_list_features_codes' => 0,
    'list_only' => 0,
    'f_code' => 0,
    'p' => 0,
    'features' => 0,
    'sku' => 0,
    'hide_quickbuy' => 0,
    'wrapper' => 0,
    'item_id' => 0,
    'hide_bd_class' => 0,
    '_quickbuy_button' => 0,
    '_product_image_src' => 0,
    'wa_parent_theme_url' => 0,
    '_saving_percent' => 0,
    'theme_favorite' => 0,
    'compare' => 0,
    'c' => 0,
    '_product_schema_image' => 0,
    'i' => 0,
    '_rating' => 0,
    'hide_description' => 0,
    '_i' => 0,
    'f_value' => 0,
    'color' => 0,
    '_sku' => 0,
    'available' => 0,
    'pre_order_only' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.14',
  'unifunc' => 'content_5fe034b865a4b2_41002994',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_5fe034b865a4b2_41002994')) {function content_5fe034b865a4b2_41002994($_smarty_tpl) {?><?php if (!is_callable('smarty_modifier_replace')) include '/var/www/u1240732/data/www/mirschetok.ru/wa-system/vendors/smarty3/plugins/modifier.replace.php';
?><?php $_smarty_tpl->tpl_vars['_products_list_features_limit'] = new Smarty_variable(isset($_smarty_tpl->tpl_vars['category']->value)&&isset($_smarty_tpl->tpl_vars['category']->value['params']['products_features_limit'])&&(!empty($_smarty_tpl->tpl_vars['category']->value['params']['products_features_limit'])||$_smarty_tpl->tpl_vars['category']->value['params']['products_features_limit']=="0") ? $_smarty_tpl->tpl_vars['category']->value['params']['products_features_limit'] : $_smarty_tpl->tpl_vars['theme_settings']->value['products_list_features_limit'], null, 0);?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_features']!="none"&&isset($_smarty_tpl->tpl_vars['show_features']->value)&&$_smarty_tpl->tpl_vars['_products_list_features_limit']->value>0){?><?php $_smarty_tpl->tpl_vars['features'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->features($_smarty_tpl->tpl_vars['products']->value), null, 0);?><?php $_smarty_tpl->tpl_vars['_products_list_features_codes'] = new Smarty_variable(isset($_smarty_tpl->tpl_vars['category']->value)&&!empty($_smarty_tpl->tpl_vars['category']->value['params']['products_features_codes']) ? $_smarty_tpl->tpl_vars['category']->value['params']['products_features_codes'] : $_smarty_tpl->tpl_vars['theme_settings']->value['products_list_features_codes'], null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_products_list_features_codes']->value)){?><?php $_smarty_tpl->tpl_vars['_products_list_features_codes'] = new Smarty_variable(explode(",",$_smarty_tpl->tpl_vars['_products_list_features_codes']->value), null, 0);?><?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_wishlist']){?><?php $_smarty_tpl->tpl_vars['theme_favorite'] = new Smarty_variable(explode(",",waRequest::cookie('shop_favorite')), null, 0);?><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_compare']){?><?php $_smarty_tpl->tpl_vars['compare'] = new Smarty_variable(explode(",",waRequest::cookie('shop_compare')), null, 0);?><?php }?><?php if (!isset($_smarty_tpl->tpl_vars['list_only']->value)){?><div class="ui-items"><div class="ui-items__wrapper"><?php }?><?php  $_smarty_tpl->tpl_vars['p'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['p']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['products']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['p']->key => $_smarty_tpl->tpl_vars['p']->value){
$_smarty_tpl->tpl_vars['p']->_loop = true;
?><?php $_smarty_tpl->createLocalArrayVariable('p', null, 0);
$_smarty_tpl->tpl_vars['p']->value['_selected_features'] = array();?><?php if (!empty($_smarty_tpl->tpl_vars['_products_list_features_codes']->value)){?><?php  $_smarty_tpl->tpl_vars['f_code'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['f_code']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_products_list_features_codes']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['f_code']->key => $_smarty_tpl->tpl_vars['f_code']->value){
$_smarty_tpl->tpl_vars['f_code']->_loop = true;
?><?php if (isset($_smarty_tpl->tpl_vars['p']->value['features'][$_smarty_tpl->tpl_vars['f_code']->value])){?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_features_color_singly']&&$_smarty_tpl->tpl_vars['features']->value[$_smarty_tpl->tpl_vars['f_code']->value]['type']=='color'){?><?php $_smarty_tpl->createLocalArrayVariable('p', null, 0);
$_smarty_tpl->tpl_vars['p']->value['_features_color'] = $_smarty_tpl->tpl_vars['p']->value['features'][$_smarty_tpl->tpl_vars['f_code']->value];?><?php }else{ ?><?php $_smarty_tpl->createLocalArrayVariable('p', null, 0);
$_smarty_tpl->tpl_vars['p']->value['_selected_features'][$_smarty_tpl->tpl_vars['f_code']->value] = $_smarty_tpl->tpl_vars['p']->value['features'][$_smarty_tpl->tpl_vars['f_code']->value];?><?php }?><?php }?><?php } ?><?php }else{ ?><?php $_smarty_tpl->createLocalArrayVariable('p', null, 0);
$_smarty_tpl->tpl_vars['p']->value['_selected_features'] = $_smarty_tpl->tpl_vars['p']->value['features'];?><?php }?><?php $_smarty_tpl->tpl_vars['available'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->settings('ignore_stock_count')||$_smarty_tpl->tpl_vars['p']->value['count']===null||$_smarty_tpl->tpl_vars['p']->value['count']>0, null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['p']->value['skus'])&&!empty($_smarty_tpl->tpl_vars['p']->value['skus'][$_smarty_tpl->tpl_vars['p']->value['sku_id']])){?><?php $_smarty_tpl->tpl_vars['sku'] = new Smarty_variable($_smarty_tpl->tpl_vars['p']->value['skus'][$_smarty_tpl->tpl_vars['p']->value['sku_id']], null, 0);?><?php if (empty($_smarty_tpl->tpl_vars['sku']->value['available'])&&(count($_smarty_tpl->tpl_vars['p']->value['skus'])===1)){?><?php $_smarty_tpl->tpl_vars['available'] = new Smarty_variable(false, null, 0);?><?php }?><?php }?><?php $_smarty_tpl->tpl_vars['pre_order_only'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->settings('ignore_stock_count')&&$_smarty_tpl->tpl_vars['p']->value['count']!==null&&$_smarty_tpl->tpl_vars['p']->value['count']<=0, null, 0);?><?php $_smarty_tpl->tpl_vars['_product_image_src'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->productImgUrl($_smarty_tpl->tpl_vars['p']->value,"200"), null, 0);?><?php $_smarty_tpl->tpl_vars['_quickbuy_button'] = new Smarty_variable(null, null, 0);?><?php if (!isset($_smarty_tpl->tpl_vars['hide_quickbuy']->value)&&method_exists("shopQuickorderPlugin","quickorderForm")){?><?php $_smarty_tpl->tpl_vars['_quickbuy_button'] = new Smarty_variable(shopQuickorderPlugin::quickorderForm($_smarty_tpl->tpl_vars['p']->value), null, 0);?><?php }?><div class='<?php echo (($tmp = @$_smarty_tpl->tpl_vars['wrapper']->value)===null||$tmp==='' ? "ui-items__item item-c-mob-".((string)$_smarty_tpl->tpl_vars['theme_settings']->value['products_list_mobile_view']) : $tmp);?>
'<?php if (isset($_smarty_tpl->tpl_vars['item_id']->value)&&!empty($_smarty_tpl->tpl_vars['item_id']->value)){?> id="<?php echo $_smarty_tpl->tpl_vars['item_id']->value;?>
"<?php }?> itemscope itemtype="http://schema.org/Product"><div class="js-product-list-item item-c item-c_<?php echo $_smarty_tpl->tpl_vars['theme_settings']->value['products_list_view'];?>
<?php if (!isset($_smarty_tpl->tpl_vars['hide_bd_class']->value)&&$_smarty_tpl->tpl_vars['theme_settings']->value['products_border']){?> item-c_bd<?php }elseif(!isset($_smarty_tpl->tpl_vars['hide_bd_class']->value)){?> item-c_nobd<?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_equal_height']){?> item-c_equal<?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_equal_height_pname']>1){?> item-c_equal_<?php echo $_smarty_tpl->tpl_vars['theme_settings']->value['products_equal_height_pname'];?>
<?php }?> has-1-click-btn_<?php if (!empty($_smarty_tpl->tpl_vars['_quickbuy_button']->value)){?>true<?php }else{ ?>false<?php }?>"><form class="addtocart" data-title="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['p']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
" data-price="<?php echo htmlspecialchars(shop_currency_html($_smarty_tpl->tpl_vars['p']->value['price']), ENT_QUOTES, 'UTF-8', true);?>
" data-oldprice="<?php if ($_smarty_tpl->tpl_vars['p']->value['compare_price']>0){?><?php echo htmlspecialchars(shop_currency_html($_smarty_tpl->tpl_vars['p']->value['compare_price']), ENT_QUOTES, 'UTF-8', true);?>
<?php }?>" data-image="<?php echo (($tmp = @$_smarty_tpl->tpl_vars['_product_image_src']->value)===null||$tmp==='' ? ((string)$_smarty_tpl->tpl_vars['wa_parent_theme_url']->value)."img/dummy200.png" : $tmp);?>
" <?php if ($_smarty_tpl->tpl_vars['p']->value['sku_count']>1){?>data-url="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
<?php if (strpos($_smarty_tpl->tpl_vars['p']->value['frontend_url'],'?')){?>&<?php }else{ ?>?<?php }?>cart=1"<?php }?> method="post" action="<?php echo $_smarty_tpl->tpl_vars['wa']->value->getUrl('/frontendCart/add');?>
"><div class="item-c__inner"><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_mobile_view']!="full"&&!empty($_smarty_tpl->tpl_vars['p']->value['video_url'])){?><div class="item-c__has-video video-icon has-tooltip" data-title="Есть видеообзор"><span class="b-tooltip">Есть видеообзор</span></div><?php }?><div class="item-c__badges"><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_saving_label']&&$_smarty_tpl->tpl_vars['p']->value['compare_price']>$_smarty_tpl->tpl_vars['p']->value['price']){?><?php $_smarty_tpl->tpl_vars['_saving_percent'] = new Smarty_variable(0, null, 0);?><?php $_smarty_tpl->tpl_vars['_saving_percent'] = new Smarty_variable((($_smarty_tpl->tpl_vars['p']->value['compare_price']-$_smarty_tpl->tpl_vars['p']->value['price'])*100)/$_smarty_tpl->tpl_vars['p']->value['compare_price'], null, 0);?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_saving_rounding_type']=='floor'){?><?php $_smarty_tpl->tpl_vars['_saving_percent'] = new Smarty_variable(floor($_smarty_tpl->tpl_vars['_saving_percent']->value), null, 0);?><?php }elseif($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_saving_rounding_type']=='ceil'){?><?php $_smarty_tpl->tpl_vars['_saving_percent'] = new Smarty_variable(ceil($_smarty_tpl->tpl_vars['_saving_percent']->value), null, 0);?><?php }elseif($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_saving_rounding_type']=='round'){?><?php $_smarty_tpl->tpl_vars['_saving_percent'] = new Smarty_variable(round($_smarty_tpl->tpl_vars['_saving_percent']->value), null, 0);?><?php }?><?php if ($_smarty_tpl->tpl_vars['_saving_percent']->value>=$_smarty_tpl->tpl_vars['theme_settings']->value['products_show_saving_percent_min']){?><div class="item-c__badge-i"><div class="dis-badge"><svg class="icon" width="50" height="50" style="color:#ffe500"><use xlink:href="#bg-quote"></use></svg><span style="color: #000;">&minus;<?php echo $_smarty_tpl->tpl_vars['_saving_percent']->value;?>
%</span></div></div><?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['p']->value['badge']=="lowprice"){?><div class="item-c__badge-i"><div class="label label_econom" style="background-color:#FFE500">Скидка</div></div><?php }elseif($_smarty_tpl->tpl_vars['p']->value['badge']=="new"){?><div class="item-c__badge-i"><div class="label label_light" style="background-color:#1FE499">Новый</div></div><?php }elseif($_smarty_tpl->tpl_vars['p']->value['badge']=="bestseller"){?><div class="item-c__badge-i"><div class="label label_light" style="background-color:#FF2AA9">Хит продаж</div></div><?php }elseif(!empty($_smarty_tpl->tpl_vars['p']->value['badge'])){?><div class="item-c__badge-i"><div class="label label_light" style="background-color:#FF2AA9"><?php echo $_smarty_tpl->tpl_vars['p']->value['badge'];?>
</div></div><?php }?></div><div class="item-c__image-wrapper item-c__image-wrapper_fixed"><a class="item-c__image-wrapper-link" href="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
" title="<?php echo $_smarty_tpl->tpl_vars['p']->value['name'];?>
"></a><img class="js-item__image lazy-img" src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo (($tmp = @$_smarty_tpl->tpl_vars['_product_image_src']->value)===null||$tmp==='' ? ((string)$_smarty_tpl->tpl_vars['wa_parent_theme_url']->value)."img/dummy200.png" : $tmp);?>
"<?php if (!$_smarty_tpl->tpl_vars['_product_image_src']->value){?> alt="No image available"<?php }else{ ?> alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['p']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"<?php }?> /><?php if (in_array($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_view'],array(2,3,4,7))){?><div class="item-c__actions item-c__actions_top"><div class="action-btns-wrapper"><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_quickview']){?><div class="action-btns-wrapper__item action-btns-wrapper__item_quick-view"><div class="item-act-btn has-tooltip btn-quickview" data-title="Быстрый просмотр" data-url="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
"><svg class="icon" width="14" height="10"><use xlink:href="#icon-eye"></use></svg><div class="item-act-btn__text visually-hidden">Быстрый просмотр</div></div></div><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_wishlist']){?><div class="action-btns-wrapper__item"><div class="item-act-btn item-act-btn_fav has-tooltip btn-fav btn-fav-<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
<?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['theme_favorite']->value)){?> active<?php }?>" data-product="<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
" data-title="Добавить в избранное" data-active="Удалить из избранного"><svg class="icon" width="12" height="10"><use xlink:href="#icon-heart-new"></use></svg><div class="item-act-btn__text visually-hidden"><?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['theme_favorite']->value)){?>Удалить из избранного<?php }else{ ?>Добавить в избранное<?php }?></div></div></div><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_compare']){?><div class="action-btns-wrapper__item"><div class="item-act-btn item-act-btn_comp has-tooltip btn-compare btn-compare-<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
<?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['compare']->value)){?> active<?php }?>" data-title="Добавить к сравнению" data-active="Удалить из сравнения" data-url="<?php echo $_smarty_tpl->tpl_vars['wa']->value->getUrl('/frontend/compare/',array('id'=>implode(',',$_smarty_tpl->tpl_vars['compare']->value)));?>
" data-product="<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
" data-product_name="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['p']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
" data-product_url="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
" data-product_image='<?php echo (($tmp = @$_smarty_tpl->tpl_vars['_product_image_src']->value)===null||$tmp==='' ? ((string)$_smarty_tpl->tpl_vars['wa_parent_theme_url']->value)."img/dummy200.png" : $tmp);?>
'><svg class="icon" width="11" height="11"><use xlink:href="#icon-chart"></use></svg><div class="item-act-btn__text visually-hidden"><?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['compare']->value)){?>Удалить из сравнения<?php }else{ ?>Добавить к сравнению<?php }?></div></div></div><?php }?></div><?php if (in_array($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_view'],array(2))){?><button class="item-c__btn btn <?php echo smarty_modifier_replace(smarty_modifier_replace($_smarty_tpl->tpl_vars['theme_settings']->value['main_buttons_style'],'img/themebuttons/',''),'.gif','');?>
 btn_main-2 btn_text" type="submit"><span>В корзину</span><i class="hover-anim"></i></button><?php }?></div><?php }?></div><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_features_color_singly']){?><div class="item-c__colors"><?php if (isset($_smarty_tpl->tpl_vars['p']->value['_features_color'])&&!empty($_smarty_tpl->tpl_vars['p']->value['_features_color'])){?><div class="item-color-list"><?php  $_smarty_tpl->tpl_vars['c'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['c']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['p']->value['_features_color']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['c']->key => $_smarty_tpl->tpl_vars['c']->value){
$_smarty_tpl->tpl_vars['c']->_loop = true;
?><span class="item-color-list__item"><span class="item-color has-tooltip" data-title="<?php echo $_smarty_tpl->tpl_vars['c']->value->value;?>
"><span class="c-color" style="<?php echo $_smarty_tpl->tpl_vars['c']->value->style;?>
"></span></span></span><?php } ?></div><?php }?></div><?php }?><a class="item-c__title js-item__title" href="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
" title="<?php echo $_smarty_tpl->tpl_vars['p']->value['name'];?>
"><span itemprop="name"><?php echo $_smarty_tpl->tpl_vars['p']->value['name'];?>
</span></a><?php $_smarty_tpl->tpl_vars['_product_schema_image'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->productImgUrl($_smarty_tpl->tpl_vars['p']->value,'970'), null, 0);?><?php if ($_smarty_tpl->tpl_vars['_product_schema_image']->value){?><meta itemprop="image" content="<?php echo $_smarty_tpl->tpl_vars['_product_schema_image']->value;?>
"><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_reviews']){?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_rating_stars']=="always"||($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_rating_stars']=="nonempty"&&$_smarty_tpl->tpl_vars['p']->value['rating']>0)){?><?php $_smarty_tpl->tpl_vars['_rating'] = new Smarty_variable(round($_smarty_tpl->tpl_vars['p']->value['rating']), null, 0);?><div class="item-rating item-c__rating"><div class="item-rating__stars"><div class="stars stars_m"><div class="stars__list"><?php $_smarty_tpl->tpl_vars['i'] = new Smarty_Variable;$_smarty_tpl->tpl_vars['i']->step = 1;$_smarty_tpl->tpl_vars['i']->total = (int)ceil(($_smarty_tpl->tpl_vars['i']->step > 0 ? 5+1 - (1) : 1-(5)+1)/abs($_smarty_tpl->tpl_vars['i']->step));
if ($_smarty_tpl->tpl_vars['i']->total > 0){
for ($_smarty_tpl->tpl_vars['i']->value = 1, $_smarty_tpl->tpl_vars['i']->iteration = 1;$_smarty_tpl->tpl_vars['i']->iteration <= $_smarty_tpl->tpl_vars['i']->total;$_smarty_tpl->tpl_vars['i']->value += $_smarty_tpl->tpl_vars['i']->step, $_smarty_tpl->tpl_vars['i']->iteration++){
$_smarty_tpl->tpl_vars['i']->first = $_smarty_tpl->tpl_vars['i']->iteration == 1;$_smarty_tpl->tpl_vars['i']->last = $_smarty_tpl->tpl_vars['i']->iteration == $_smarty_tpl->tpl_vars['i']->total;?><div class="stars__i<?php if ($_smarty_tpl->tpl_vars['i']->value<=$_smarty_tpl->tpl_vars['_rating']->value){?> stars__i_checked<?php }?>"><svg class="icon" width="16" height="15"><use xlink:href="#icon-star"></use></svg></div><?php }} ?></div></div></div><div class="item-rating__revs"><svg class="icon" width="15" height="14"><use xlink:href="#icon-bubble"></use></svg><a class="grey" href="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
reviews/"><?php echo $_smarty_tpl->tpl_vars['p']->value['rating_count'];?>
</a></div></div><?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['p']->value['summary']&&$_smarty_tpl->tpl_vars['theme_settings']->value['products_thumbs_show_summary']&&!isset($_smarty_tpl->tpl_vars['hide_description']->value)){?><div class="item-c__short-descr grey"><span itemprop="description"><?php echo $_smarty_tpl->tpl_vars['p']->value['summary'];?>
</span></div><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_features']=="yes"){?><div class="item-chars item-c__chars"><?php if (!empty($_smarty_tpl->tpl_vars['p']->value['features'])){?><?php if (!empty($_smarty_tpl->tpl_vars['p']->value['_selected_features'])){?><ul class="item-chars__list list-reset grey"><?php $_smarty_tpl->tpl_vars['_i'] = new Smarty_variable(1, null, 0);?><?php  $_smarty_tpl->tpl_vars['f_value'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['f_value']->_loop = false;
 $_smarty_tpl->tpl_vars['f_code'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['p']->value['_selected_features']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['f_value']->key => $_smarty_tpl->tpl_vars['f_value']->value){
$_smarty_tpl->tpl_vars['f_value']->_loop = true;
 $_smarty_tpl->tpl_vars['f_code']->value = $_smarty_tpl->tpl_vars['f_value']->key;
?><?php if ($_smarty_tpl->tpl_vars['features']->value[$_smarty_tpl->tpl_vars['f_code']->value]['type']=='divider'){?><?php continue 1?><?php }?><?php if ($_smarty_tpl->tpl_vars['_i']->value>$_smarty_tpl->tpl_vars['_products_list_features_limit']->value){?><?php break 1?><?php }?><?php $_smarty_tpl->tpl_vars['_i'] = new Smarty_variable($_smarty_tpl->tpl_vars['_i']->value+1, null, 0);?><li class="item-chars__item"><dl class="cst-reset"><dt><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['features']->value[$_smarty_tpl->tpl_vars['f_code']->value]['name'], ENT_QUOTES, 'UTF-8', true);?>
:</dt><dd><?php if (is_array($_smarty_tpl->tpl_vars['f_value']->value)){?><?php if ($_smarty_tpl->tpl_vars['features']->value[$_smarty_tpl->tpl_vars['f_code']->value]['type']=='color'){?><div class="item-color-list"><?php  $_smarty_tpl->tpl_vars['color'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['color']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['f_value']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['color']->key => $_smarty_tpl->tpl_vars['color']->value){
$_smarty_tpl->tpl_vars['color']->_loop = true;
?><div class="item-color-list__item"><div class="item-color has-tooltip" data-title="<?php echo $_smarty_tpl->tpl_vars['color']->value->value;?>
"><div class="c-color" style="<?php echo $_smarty_tpl->tpl_vars['color']->value->style;?>
"></div><span class="b-tooltip"><?php echo $_smarty_tpl->tpl_vars['color']->value->value;?>
</span></div></div><?php } ?></div><?php }else{ ?><?php echo implode(', ',$_smarty_tpl->tpl_vars['f_value']->value);?>
<?php }?><?php }else{ ?><?php echo $_smarty_tpl->tpl_vars['f_value']->value;?>
<?php }?></dd></dl></li><?php } ?></ul><?php }?><?php }?></div><?php }?><div class="item-c__price"><div class="price-wrapper"><?php if ($_smarty_tpl->tpl_vars['p']->value['compare_price']>0){?><div class="price-wrapper__top"><div class="price price_old"><?php echo shop_currency_html($_smarty_tpl->tpl_vars['p']->value['compare_price']);?>
</div><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_saving_label']&&$_smarty_tpl->tpl_vars['p']->value['compare_price']>$_smarty_tpl->tpl_vars['p']->value['price']){?><div class="label" style="background-color: #ffe500;">&minus;<?php echo shop_currency_html(round($_smarty_tpl->tpl_vars['p']->value['compare_price']-$_smarty_tpl->tpl_vars['p']->value['price']));?>
</div><?php }?></div><?php }?><div class="price-wrapper__main"><div class="price price_main"><?php echo shop_currency_html($_smarty_tpl->tpl_vars['p']->value['price']);?>
</div></div></div></div><?php if (!empty($_smarty_tpl->tpl_vars['p']->value['skus'])&&!empty($_smarty_tpl->tpl_vars['p']->value['skus'][$_smarty_tpl->tpl_vars['p']->value['sku_id']])){?><?php $_smarty_tpl->tpl_vars['_sku'] = new Smarty_variable($_smarty_tpl->tpl_vars['p']->value['skus'][$_smarty_tpl->tpl_vars['p']->value['sku_id']], null, 0);?><?php if ((count($_smarty_tpl->tpl_vars['p']->value['skus'])===1)&&!empty($_smarty_tpl->tpl_vars['_sku']->value['sku'])){?><div class="item-c__sku grey">Артикул: <?php echo $_smarty_tpl->tpl_vars['_sku']->value['sku'];?>
</div><meta itemprop="sku" content="<?php echo $_smarty_tpl->tpl_vars['_sku']->value['sku'];?>
"><?php }?><?php }?><div class="stock-info stock item-c__stock-info"><?php if ($_smarty_tpl->tpl_vars['available']->value){?><?php if ($_smarty_tpl->tpl_vars['pre_order_only']->value){?><div class="stock-info less-stock"><svg class="icon" width="10" height="7"><use xlink:href="#icon-tick"></use></svg><div class="stock-info__text">Под заказ</div></div><?php }else{ ?><svg class="icon" width="10" height="7"><use xlink:href="#icon-tick"></use></svg><div class="stock-info__text">В наличии</div><?php }?><?php }else{ ?><div class="stock-info no-stock"><div class="stock-info__text">Нет в наличии</div></div><?php }?></div><div class="item-c__actions-wrapper"><div class="item-c__top"><?php if (in_array($_smarty_tpl->tpl_vars['theme_settings']->value['products_list_view'],array(7))){?><div class="item-c__qty"><div class="qty"><div class="qty__inner"><button class="qty__btn qty__btn_decr default-btn" type="button"><svg class="icon" width="9" height="9"><use xlink:href="#icon-minus"></use></svg></button><input class="qty__field" type="text" name="quantity" value="1"><button class="qty__btn qty__btn_incr default-btn" type="button"><svg class="icon" width="9" height="9"><use xlink:href="#icon-plus"></use></svg></button></div></div></div><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_quickview']||$_smarty_tpl->tpl_vars['theme_settings']->value['products_show_compare']||$_smarty_tpl->tpl_vars['theme_settings']->value['products_show_wishlist']){?><div class="item-c__actions"><div class="action-btns-wrapper"><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_quickview']){?><div class="action-btns-wrapper__item action-btns-wrapper__item_quick-view"><div class="item-act-btn has-tooltip btn-quickview" data-title="Быстрый просмотр" data-url="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
"><svg class="icon" width="14" height="10"><use xlink:href="#icon-eye"></use></svg><div class="item-act-btn__text visually-hidden">Быстрый просмотр</div></div></div><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_wishlist']){?><div class="action-btns-wrapper__item"><div class="item-act-btn item-act-btn_fav has-tooltip btn-fav btn-fav-<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
<?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['theme_favorite']->value)){?> active<?php }?>" data-product="<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
" data-title="Добавить в избранное" data-active="Удалить из избранного"><svg class="icon" width="12" height="10"><use xlink:href="#icon-heart-new"></use></svg><div class="item-act-btn__text visually-hidden"><?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['theme_favorite']->value)){?>Удалить из избранного<?php }else{ ?>Добавить в избранное<?php }?></div></div></div><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_show_compare']){?><div class="action-btns-wrapper__item"><div class="item-act-btn item-act-btn_comp has-tooltip btn-compare btn-compare-<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
<?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['compare']->value)){?> active<?php }?>" data-title="Добавить к сравнению" data-active="Удалить из сравнения" data-url="<?php echo $_smarty_tpl->tpl_vars['wa']->value->getUrl('/frontend/compare/',array('id'=>implode(',',$_smarty_tpl->tpl_vars['compare']->value)));?>
" data-product="<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
" data-product_name="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['p']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
" data-product_url="<?php echo $_smarty_tpl->tpl_vars['p']->value['frontend_url'];?>
" data-product_image='<?php echo (($tmp = @$_smarty_tpl->tpl_vars['_product_image_src']->value)===null||$tmp==='' ? ((string)$_smarty_tpl->tpl_vars['wa_parent_theme_url']->value)."img/dummy200.png" : $tmp);?>
'><svg class="icon" width="11" height="11"><use xlink:href="#icon-chart"></use></svg><div class="item-act-btn__text visually-hidden"><?php if (in_array($_smarty_tpl->tpl_vars['p']->value['id'],$_smarty_tpl->tpl_vars['compare']->value)){?>Удалить из сравнения<?php }else{ ?>Добавить к сравнению<?php }?></div></div></div><?php }?></div></div><?php }?><button class="item-c__btn btn <?php echo smarty_modifier_replace(smarty_modifier_replace($_smarty_tpl->tpl_vars['theme_settings']->value['main_buttons_style'],'img/themebuttons/',''),'.gif','');?>
 btn_main-2 btn_text" type="submit"<?php if (!$_smarty_tpl->tpl_vars['available']->value){?> disabled="disabled"<?php }?>><span>В корзину</span><i class="hover-anim"></i></button></div><?php if (!empty($_smarty_tpl->tpl_vars['_quickbuy_button']->value)){?><div class="item-c__one-click item-c__one-click_tiled"><?php echo $_smarty_tpl->tpl_vars['_quickbuy_button']->value;?>
</div><?php }?></div></div><span itemprop="offers" class="offers" itemscope itemtype="http://schema.org/Offer"><?php if ($_smarty_tpl->tpl_vars['available']->value){?><meta itemprop="price" content="<?php echo shop_currency($_smarty_tpl->tpl_vars['p']->value['price'],null,null,0);?>
"><meta itemprop="priceCurrency" content="<?php echo $_smarty_tpl->tpl_vars['wa']->value->shop->currency();?>
"><link itemprop="availability" href="http://schema.org/InStock" /><?php }else{ ?><meta itemprop="price" content="<?php echo shop_currency($_smarty_tpl->tpl_vars['p']->value['price'],null,null,0);?>
"><meta itemprop="priceCurrency" content="<?php echo $_smarty_tpl->tpl_vars['wa']->value->shop->currency();?>
"><link itemprop="availability" href="http://schema.org/OutOfStock" /><?php }?></span><input type="hidden" name="product_id" value="<?php echo $_smarty_tpl->tpl_vars['p']->value['id'];?>
"></form></div></div><?php } ?><?php if (!isset($_smarty_tpl->tpl_vars['list_only']->value)){?></div></div><?php }?><?php }} ?>