<?php /* Smarty version Smarty-3.1.14, created on 2020-12-21 08:37:58
         compiled from "/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/category.html" */ ?>
<?php /*%%SmartyHeaderCode:15959156865fe034b69d6a00-40980211%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '5ebfbcc3bccf4d24bf28c15a65f79a84200c10ad' => 
    array (
      0 => '/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/category.html',
      1 => 1596613227,
      2 => 'file',
    ),
    '92a2f4664df3ef4adce17cba2b01dcd0979faaaa' => 
    array (
      0 => '/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/system.category.html',
      1 => 1596613227,
      2 => 'file',
    ),
    '5e6b2622288357f63afa4ad9ab437a6ff9cc508f' => 
    array (
      0 => '/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/category.subcategories.html',
      1 => 1596613227,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '15959156865fe034b69d6a00-40980211',
  'function' => 
  array (
    'breadcrumbs_tree' => 
    array (
      'parameter' => 
      array (
      ),
      'compiled' => '',
    ),
  ),
  'variables' => 
  array (
    'category' => 0,
    'breadcrumbs' => 0,
    'theme_settings' => 0,
    'wa_url' => 0,
    'wa' => 0,
    '_categories_tree' => 0,
    'tree' => 0,
    'c' => 0,
    'sc' => 0,
    'bc' => 0,
    '_theme_config' => 0,
    'section' => 0,
    '_theme_config_bars' => 0,
    'filters' => 0,
    'products' => 0,
    'frontend_category' => 0,
    '_' => 0,
    '_theme_products_view_mode' => 0,
    'pages_count' => 0,
    'wa_parent_theme_path' => 0,
    'wa_backend_url' => 0,
  ),
  'has_nocache_code' => 0,
  'version' => 'Smarty-3.1.14',
  'unifunc' => 'content_5fe034b7a29e51_58312418',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_5fe034b7a29e51_58312418')) {function content_5fe034b7a29e51_58312418($_smarty_tpl) {?><?php if (!is_callable('smarty_function_wa_pagination')) include '/var/www/u1240732/data/www/mirschetok.ru/wa-system/vendors/smarty-plugins/function.wa_pagination.php';
?><?php /*  Call merged included template "system.category.html" */
$_tpl_stack[] = $_smarty_tpl;
 $_smarty_tpl = $_smarty_tpl->setupInlineSubTemplate("system.category.html", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 1, '15959156865fe034b69d6a00-40980211');
content_5fe034b6a036a0_33345361($_smarty_tpl);
$_smarty_tpl = array_pop($_tpl_stack); /*  End of included template "system.category.html" */?><div class="catalog-pg"><?php if ($_smarty_tpl->tpl_vars['category']->value['parent_id']&&!empty($_smarty_tpl->tpl_vars['breadcrumbs']->value)){?><div class="layout-center"><div class="breadcrumbs breadcrumbs_<?php echo $_smarty_tpl->tpl_vars['theme_settings']->value['breadcrumbs_design'];?>
"><ul class="breadcrumbs__list"><li class="breadcrumbs__item"><a class="breadcrumbs__link" href="<?php echo $_smarty_tpl->tpl_vars['wa_url']->value;?>
">Главная</a></li><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['breadcrumbs_design']=="dropdown"){?><?php $_smarty_tpl->tpl_vars['_categories_tree'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->categories(0,$_smarty_tpl->tpl_vars['category']->value['depth'],true), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_categories_tree']->value)){?><?php if (!function_exists('smarty_template_function_breadcrumbs_tree')) {
    function smarty_template_function_breadcrumbs_tree($_smarty_tpl,$params) {
    $saved_tpl_vars = $_smarty_tpl->tpl_vars;
    foreach ($_smarty_tpl->smarty->template_functions['breadcrumbs_tree']['parameter'] as $key => $value) {$_smarty_tpl->tpl_vars[$key] = new Smarty_variable($value);};
    foreach ($params as $key => $value) {$_smarty_tpl->tpl_vars[$key] = new Smarty_variable($value);}?><?php  $_smarty_tpl->tpl_vars['c'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['c']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['tree']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['c']->key => $_smarty_tpl->tpl_vars['c']->value){
$_smarty_tpl->tpl_vars['c']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['c']->value['left_key']<$_smarty_tpl->tpl_vars['category']->value['left_key']&&$_smarty_tpl->tpl_vars['c']->value['right_key']>$_smarty_tpl->tpl_vars['category']->value['right_key']){?><li class="breadcrumbs__item"><a class="breadcrumbs__link" href="<?php echo $_smarty_tpl->tpl_vars['c']->value['url'];?>
"><?php echo $_smarty_tpl->tpl_vars['c']->value['name'];?>
</a><?php if (count($_smarty_tpl->tpl_vars['tree']->value)>1){?><div class="breadcrumbs__btn"><svg class="icon" width="6" height="4"><use xlink:href="#arrow-up-breadcrumb"></use></svg></div><ul class="breadcrumbs__dropdown"><?php  $_smarty_tpl->tpl_vars['sc'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['sc']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['tree']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['sc']->key => $_smarty_tpl->tpl_vars['sc']->value){
$_smarty_tpl->tpl_vars['sc']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['sc']->value['id']==$_smarty_tpl->tpl_vars['c']->value['id']){?><?php continue 1?><?php }?><li class="breadcrumbs__dropdown-i"><a class="breadcrumbs__link" href="<?php echo $_smarty_tpl->tpl_vars['sc']->value['url'];?>
"><?php echo $_smarty_tpl->tpl_vars['sc']->value['name'];?>
</a></li><?php } ?></ul><?php }?></li><?php smarty_template_function_breadcrumbs_tree($_smarty_tpl,array('tree'=>$_smarty_tpl->tpl_vars['c']->value['childs']));?>
<?php }?><?php } ?><?php $_smarty_tpl->tpl_vars = $saved_tpl_vars;
foreach (Smarty::$global_tpl_vars as $key => $value) if(!isset($_smarty_tpl->tpl_vars[$key])) $_smarty_tpl->tpl_vars[$key] = $value;}}?>
<?php smarty_template_function_breadcrumbs_tree($_smarty_tpl,array('tree'=>$_smarty_tpl->tpl_vars['_categories_tree']->value));?>
<?php }?><?php }else{ ?><?php  $_smarty_tpl->tpl_vars['bc'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['bc']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['breadcrumbs']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['bc']->key => $_smarty_tpl->tpl_vars['bc']->value){
$_smarty_tpl->tpl_vars['bc']->_loop = true;
?><li class="breadcrumbs__item"><a class="breadcrumbs__link" href="<?php echo $_smarty_tpl->tpl_vars['bc']->value['url'];?>
"><?php echo $_smarty_tpl->tpl_vars['bc']->value['name'];?>
</a></li><?php } ?><?php }?></ul></div></div><?php }?><div class="layout-center"><h1 class="catalog-pg__title category-name"><?php echo htmlspecialchars($_smarty_tpl->tpl_vars['category']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
</h1></div><?php if (!empty($_smarty_tpl->tpl_vars['category']->value['params']['image_banner'])){?><div class="layout-center"><div class="cat-top-bannner"><?php if (!empty($_smarty_tpl->tpl_vars['category']->value['params']['image_banner_url'])){?><a href="<?php echo $_smarty_tpl->tpl_vars['category']->value['params']['image_banner_url'];?>
"><?php }?><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo $_smarty_tpl->tpl_vars['category']->value['params']['image_banner'];?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['category']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"><?php if (!empty($_smarty_tpl->tpl_vars['category']->value['params']['image_banner_url'])){?></a><?php }?></div></div><?php }else{ ?><?php if (method_exists("shopWmimageincatPlugin","getCategoryImage")){?><?php if (shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['category']->value['id'],'banner')){?><div class="layout-center"><div class="cat-top-bannner"><?php if (!empty($_smarty_tpl->tpl_vars['category']->value['params']['image_banner_url'])){?><a href="<?php echo $_smarty_tpl->tpl_vars['category']->value['params']['image_banner_url'];?>
"><?php }?><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['category']->value['id'],'banner');?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['category']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"><?php if (!empty($_smarty_tpl->tpl_vars['category']->value['params']['image_banner_url'])){?></a><?php }?></div></div><?php }?><?php }?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['category']->value['subcategories'])&&$_smarty_tpl->tpl_vars['theme_settings']->value['products_subcategories_view']!="none"){?><div class="layout-center"><?php /*  Call merged included template "category.subcategories.html" */
$_tpl_stack[] = $_smarty_tpl;
 $_smarty_tpl = $_smarty_tpl->setupInlineSubTemplate("category.subcategories.html", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0, '15959156865fe034b69d6a00-40980211');
content_5fe034b767e556_83516902($_smarty_tpl);
$_smarty_tpl = array_pop($_tpl_stack); /*  End of included template "category.subcategories.html" */?></div><?php }?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_description_location']=="top"&&$_smarty_tpl->tpl_vars['category']->value['description']&&!waRequest::get('page',0)){?><div class="layout-center"><div class="catalog-pg__descr category-desc"><?php echo $_smarty_tpl->tpl_vars['category']->value['description'];?>
</div></div><?php }?><div class="catalog-pg__main b-row"><div class="b-row__inner"><?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'])){?><aside class="catalog-pg__sidebar catalog-pg__sidebar_menu col-1-of-5"><?php  $_smarty_tpl->tpl_vars['section'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['section']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_theme_config']->value['leftbar']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['section']->key => $_smarty_tpl->tpl_vars['section']->value){
$_smarty_tpl->tpl_vars['section']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['section']->value['type']=="section"){?><?php echo $_smarty_tpl->getSubTemplate ("sidebar.".((string)$_smarty_tpl->tpl_vars['section']->value['value']).".html", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
<?php }else{ ?><div class="catalog-pg__side-sect mt-hide"><div class="sidebar-section"><?php echo $_smarty_tpl->getSubTemplate ("string:".((string)$_smarty_tpl->tpl_vars['section']->value['value']), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</div></div><?php }?><?php } ?></aside><?php }?><div class="catalog-pg__content col-<?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'])){?><?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'])){?>3<?php }else{ ?>4<?php }?><?php }else{ ?>4<?php }?>-of-5"><?php if (isset($_smarty_tpl->tpl_vars['_theme_config_bars']->value)&&!empty($_smarty_tpl->tpl_vars['_theme_config_bars']->value)){?><?php if ((in_array("filters",$_smarty_tpl->tpl_vars['_theme_config_bars']->value)&&isset($_smarty_tpl->tpl_vars['filters']->value)&&!empty($_smarty_tpl->tpl_vars['filters']->value))){?><div class="catalog-pg__adaptive-btns"><div class="catalog-pg__toggle-panel" data-sidebar-btn="filters"><svg class="icon" width="16" height="16"><use xlink:href="#icon-filter"></use></svg><strong>Фильтр</strong></div></div><?php }?><?php }?><?php if ($_smarty_tpl->tpl_vars['products']->value){?><?php echo $_smarty_tpl->getSubTemplate ("category.sorting.html", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array('sorting'=>!empty($_smarty_tpl->tpl_vars['category']->value['params']['enable_sorting'])), 0);?>
<?php }?><!-- plugin hook: 'frontend_category' --><?php  $_smarty_tpl->tpl_vars['_'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['_']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['frontend_category']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['_']->key => $_smarty_tpl->tpl_vars['_']->value){
$_smarty_tpl->tpl_vars['_']->_loop = true;
?><?php echo $_smarty_tpl->tpl_vars['_']->value;?>
<?php } ?><div class="catalog-pg__items"><div id="product-list"><?php if (!$_smarty_tpl->tpl_vars['products']->value){?><?php if (!empty($_smarty_tpl->tpl_vars['filters']->value)){?><div class="acc-info-box"><div class="acc-info-box__title">Не найдено ни одного товара.</div></div><?php }else{ ?><div class="acc-info-box"><div class="acc-info-box__text">В этой категории нет ни одного товара.</div></div><?php }?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_theme_products_view_mode'] = new Smarty_variable(waRequest::cookie('_theme_products_view_mode',$_smarty_tpl->tpl_vars['theme_settings']->value['products_mode_default']), null, 0);?><?php if (!in_array($_smarty_tpl->tpl_vars['_theme_products_view_mode']->value,array("thumbs","expanded","compact"))){?><?php $_smarty_tpl->tpl_vars['_theme_products_view_mode'] = new Smarty_variable("thumbs", null, 0);?><?php }?><?php echo $_smarty_tpl->getSubTemplate ("list-".((string)$_smarty_tpl->tpl_vars['_theme_products_view_mode']->value).".html", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array('show_features'=>true), 0);?>
<?php if (isset($_smarty_tpl->tpl_vars['pages_count']->value)&&$_smarty_tpl->tpl_vars['pages_count']->value>1){?><div class="catalog-pg__pagination"><div class="pagination lazyloading-paging"  data-times="2" data-link-text="Загрузить еще" data-loading-str="Загрузка..."><?php echo smarty_function_wa_pagination(array('total'=>$_smarty_tpl->tpl_vars['pages_count']->value,'attrs'=>array('class'=>"pagination__list")),$_smarty_tpl);?>
</div></div><?php }?><?php }?></div></div><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['products_description_location']=="bottom"&&$_smarty_tpl->tpl_vars['category']->value['description']&&!waRequest::get('page',0)){?><div class="catalog-pg__seo-text category-desc"><?php echo $_smarty_tpl->tpl_vars['category']->value['description'];?>
</div><?php }?></div><?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'])){?><aside class="catalog-pg__sidebar catalog-pg__sidebar_menu col-1-of-5"><?php  $_smarty_tpl->tpl_vars['section'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['section']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_theme_config']->value['rightbar']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['section']->key => $_smarty_tpl->tpl_vars['section']->value){
$_smarty_tpl->tpl_vars['section']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['section']->value['type']=="section"){?><?php echo $_smarty_tpl->getSubTemplate ("sidebar.".((string)$_smarty_tpl->tpl_vars['section']->value['value']).".html", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
<?php }else{ ?><div class="catalog-pg__side-sect mt-hide"><div class="sidebar-section"><?php echo $_smarty_tpl->getSubTemplate ("string:".((string)$_smarty_tpl->tpl_vars['section']->value['value']), $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array(), 0);?>
</div></div><?php }?><?php } ?></aside><?php }?><div class="bg-overlay"></div></div></div></div><?php if ($_smarty_tpl->tpl_vars['wa']->value->user()->isAdmin()){?><a class="show-toggle-btn" href="#"><svg class="icon cent-icon" width="18" height="18"><use xlink:href="#icon-info"></use></svg></a><?php }?><?php if (isset($_smarty_tpl->tpl_vars['category']->value)){?><?php echo $_smarty_tpl->getSubTemplate (((string)$_smarty_tpl->tpl_vars['wa_parent_theme_path']->value)."/admin_edit_button.html", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, null, null, array('link'=>((string)$_smarty_tpl->tpl_vars['wa_backend_url']->value)."shop/?action=products#/products/category_id=".((string)$_smarty_tpl->tpl_vars['category']->value['id']),'title'=>"Редактировать категорию"), 0);?>
<?php }?><?php }} ?><?php /* Smarty version Smarty-3.1.14, created on 2020-12-21 08:37:58
         compiled from "/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/system.category.html" */ ?>
<?php if ($_valid && !is_callable('content_5fe034b6a036a0_33345361')) {function content_5fe034b6a036a0_33345361($_smarty_tpl) {?><?php if (!is_callable('smarty_modifier_replace')) include '/var/www/u1240732/data/www/mirschetok.ru/wa-system/vendors/smarty3/plugins/modifier.replace.php';
?><?php $_smarty_tpl->tpl_vars['_theme_config'] = new Smarty_variable(array(), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['sorting']->value)){?><?php $_smarty_tpl->tpl_vars['sort_fields'] = new Smarty_variable(array('create_datetime'=>'Дата добавления','price'=>'Цена','name'=>'Название'), null, 0);?><?php $_smarty_tpl->tpl_vars['active_sort'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->get('sort','create_datetime'), null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['_theme_config_leftbar'] = new Smarty_variable(isset($_smarty_tpl->tpl_vars['category']->value)&&isset($_smarty_tpl->tpl_vars['category']->value['params']['balance_catalog_leftbar']) ? $_smarty_tpl->tpl_vars['category']->value['params']['balance_catalog_leftbar'] : $_smarty_tpl->tpl_vars['theme_settings']->value['shop_catalog_grid_leftbar'], null, 0);?><?php $_smarty_tpl->tpl_vars['_theme_config_leftbar'] = new Smarty_variable(explode(",",$_smarty_tpl->tpl_vars['_theme_config_leftbar']->value), null, 0);?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'] = array();?><?php  $_smarty_tpl->tpl_vars['section'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['section']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_theme_config_leftbar']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['section']->key => $_smarty_tpl->tpl_vars['section']->value){
$_smarty_tpl->tpl_vars['section']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['section'] = new Smarty_variable(trim($_smarty_tpl->tpl_vars['section']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['section']->value=="viewed"){?><?php $_smarty_tpl->tpl_vars['_viewed_pids'] = new Smarty_variable(waRequest::cookie('balance_viewed'), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_viewed_pids']->value)){?><?php $_smarty_tpl->tpl_vars['_viewed_products'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->products("id/".((string)$_smarty_tpl->tpl_vars['_viewed_pids']->value),5), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_viewed_products']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="filters"){?><?php if (isset($_smarty_tpl->tpl_vars['filters']->value)&&!empty($_smarty_tpl->tpl_vars['filters']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="tags"){?><?php $_smarty_tpl->tpl_vars['_shop_tags'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->tags(15), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_shop_tags']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="categories"){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['categories_links'] = $_smarty_tpl->tpl_vars['wa']->value->shop->categories(0,3,true,true);?><?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['categories_links'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="menu"){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'] = $_smarty_tpl->tpl_vars['wa']->value->shop->categories(0,3,true,true);?><?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'])){?><?php  $_smarty_tpl->tpl_vars['cat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['cat']->_loop = false;
 $_smarty_tpl->tpl_vars['id'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['cat']->key => $_smarty_tpl->tpl_vars['cat']->value){
$_smarty_tpl->tpl_vars['cat']->_loop = true;
 $_smarty_tpl->tpl_vars['id']->value = $_smarty_tpl->tpl_vars['cat']->key;
?><?php if (isset($_smarty_tpl->tpl_vars['cat']->value['params']['childs_grid'])&&!empty($_smarty_tpl->tpl_vars['cat']->value['params']['childs_grid'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['_childs_grid'] = $_smarty_tpl->tpl_vars['cat']->value['params']['childs_grid'];?><?php }?><?php if (isset($_smarty_tpl->tpl_vars['cat']->value['params']['menu_icon'])&&!empty($_smarty_tpl->tpl_vars['cat']->value['params']['menu_icon'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['menu_icon'] = $_smarty_tpl->tpl_vars['cat']->value['params']['menu_icon'];?><?php }elseif(method_exists("shopWmimageincatPlugin","getCategoryImage")&&shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['cat']->value['id'],'icon')){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['menu_icon'] = shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['cat']->value['id'],'icon');?><?php }else{ ?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['menu_icon'] = '';?><?php }?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['submenu_mono_viewtype'] = (($tmp = @$_smarty_tpl->tpl_vars['cat']->value['params']['submenu_mono_viewtype'])===null||$tmp==='' ? $_smarty_tpl->tpl_vars['theme_settings']->value['mainmenu_submenu_mono_viewtype'] : $tmp);?><?php if (!empty($_smarty_tpl->tpl_vars['cat']->value['childs'])){?><?php  $_smarty_tpl->tpl_vars['subcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subcat']->_loop = false;
 $_smarty_tpl->tpl_vars['sub_id'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['cat']->value['childs']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subcat']->key => $_smarty_tpl->tpl_vars['subcat']->value){
$_smarty_tpl->tpl_vars['subcat']->_loop = true;
 $_smarty_tpl->tpl_vars['sub_id']->value = $_smarty_tpl->tpl_vars['subcat']->key;
?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['submenu_mono_viewtype'] = (($tmp = @$_smarty_tpl->tpl_vars['subcat']->value['params']['submenu_mono_viewtype'])===null||$tmp==='' ? $_smarty_tpl->tpl_vars['theme_settings']->value['mainmenu_submenu_mono_viewtype'] : $tmp);?><?php if (isset($_smarty_tpl->tpl_vars['subcat']->value['params']['menu_icon'])&&!empty($_smarty_tpl->tpl_vars['subcat']->value['params']['menu_icon'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['menu_icon'] = $_smarty_tpl->tpl_vars['subcat']->value['params']['menu_icon'];?><?php }elseif(method_exists("shopWmimageincatPlugin","getCategoryImage")&&shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'icon')){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['menu_icon'] = shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'icon');?><?php }else{ ?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['menu_icon'] = '';?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['subcat']->value['childs'])){?><?php  $_smarty_tpl->tpl_vars['subsubcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subsubcat']->_loop = false;
 $_smarty_tpl->tpl_vars['subsub_id'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['subcat']->value['childs']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subsubcat']->key => $_smarty_tpl->tpl_vars['subsubcat']->value){
$_smarty_tpl->tpl_vars['subsubcat']->_loop = true;
 $_smarty_tpl->tpl_vars['subsub_id']->value = $_smarty_tpl->tpl_vars['subsubcat']->key;
?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['submenu_mono_viewtype'] = (($tmp = @$_smarty_tpl->tpl_vars['subsubcat']->value['params']['submenu_mono_viewtype'])===null||$tmp==='' ? $_smarty_tpl->tpl_vars['theme_settings']->value['mainmenu_submenu_mono_viewtype'] : $tmp);?><?php if (isset($_smarty_tpl->tpl_vars['subsubcat']->value['params']['menu_icon'])&&!empty($_smarty_tpl->tpl_vars['subsubcat']->value['params']['menu_icon'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['menu_icon'] = $_smarty_tpl->tpl_vars['subsubcat']->value['params']['menu_icon'];?><?php }elseif(method_exists("shopWmimageincatPlugin","getCategoryImage")&&shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subsubcat']->value['id'],'icon')){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['menu_icon'] = shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subsubcat']->value['id'],'icon');?><?php }else{ ?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['menu_icon'] = '';?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['subsubcat']->value['childs'])){?><?php  $_smarty_tpl->tpl_vars['subsubsubcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subsubsubcat']->_loop = false;
 $_smarty_tpl->tpl_vars['subsubcat_id'] = new Smarty_Variable;
 $_from = $_smarty_tpl->tpl_vars['subsubcat']->value['childs']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subsubsubcat']->key => $_smarty_tpl->tpl_vars['subsubsubcat']->value){
$_smarty_tpl->tpl_vars['subsubsubcat']->_loop = true;
 $_smarty_tpl->tpl_vars['subsubcat_id']->value = $_smarty_tpl->tpl_vars['subsubsubcat']->key;
?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsubcat_id']->value]['submenu_mono_viewtype'] = (($tmp = @$_smarty_tpl->tpl_vars['subsubsubcat']->value['params']['submenu_mono_viewtype'])===null||$tmp==='' ? $_smarty_tpl->tpl_vars['theme_settings']->value['mainmenu_submenu_mono_viewtype'] : $tmp);?><?php if (isset($_smarty_tpl->tpl_vars['subsubsubcat']->value['params']['menu_icon'])&&!empty($_smarty_tpl->tpl_vars['subsubsubcat']->value['params']['menu_icon'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsubcat_id']->value]['menu_icon'] = $_smarty_tpl->tpl_vars['subsubsubcat']->value['params']['menu_icon'];?><?php }elseif(method_exists("shopWmimageincatPlugin","getCategoryImage")&&shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subsubsubcat']->value['id'],'icon')){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsubcat_id']->value]['menu_icon'] = shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subsubsubcat']->value['id'],'icon');?><?php }else{ ?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'][$_smarty_tpl->tpl_vars['id']->value]['childs'][$_smarty_tpl->tpl_vars['sub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsub_id']->value]['childs'][$_smarty_tpl->tpl_vars['subsubcat_id']->value]['menu_icon'] = '';?><?php }?><?php } ?><?php }?><?php } ?><?php }?><?php } ?><?php }?><?php } ?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="productbrands"){?><?php if (method_exists("shopProductbrandsPlugin","getBrands")){?><?php $_smarty_tpl->tpl_vars['_shop_brands'] = new Smarty_variable(shopProductbrandsPlugin::getBrands(), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_shop_brands']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="last-posts"){?><?php if ($_smarty_tpl->tpl_vars['wa']->value->blog){?><?php $_smarty_tpl->tpl_vars['sidebar_posts'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->blog->posts(null,2), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['sidebar_posts']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="products"){?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_products_limit']>0){?><?php $_smarty_tpl->tpl_vars['limit'] = new Smarty_variable($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_products_limit'], null, 0);?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['limit'] = new Smarty_variable(4, null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['sidebar_products'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->productSet($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_products_set'],$_smarty_tpl->tpl_vars['limit']->value), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['sidebar_products']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="faq"){?><?php $_smarty_tpl->tpl_vars['_faq'] = new Smarty_variable(array(), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_1_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_1_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_1_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_2_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_2_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_2_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_3_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_3_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_3_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_4_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_4_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_4_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_5_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_5_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_5_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['_faq']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="about"){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }elseif(substr($_smarty_tpl->tpl_vars['section']->value,0,6)=="block="){?><?php $_smarty_tpl->tpl_vars['sidebar_block'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->block(smarty_modifier_replace($_smarty_tpl->tpl_vars['section']->value,"block=",'')), null, 0);?><?php if ($_smarty_tpl->tpl_vars['sidebar_block']->value){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['leftbar'][] = array('type'=>'block','value'=>$_smarty_tpl->tpl_vars['sidebar_block']->value);?><?php }?><?php }?><?php } ?><?php $_smarty_tpl->tpl_vars['_theme_config_rightbar'] = new Smarty_variable(isset($_smarty_tpl->tpl_vars['category']->value)&&isset($_smarty_tpl->tpl_vars['category']->value['params']['balance_catalog_rightbar']) ? $_smarty_tpl->tpl_vars['category']->value['params']['balance_catalog_rightbar'] : $_smarty_tpl->tpl_vars['theme_settings']->value['shop_catalog_grid_rightbar'], null, 0);?><?php $_smarty_tpl->tpl_vars['_theme_config_rightbar'] = new Smarty_variable(explode(",",$_smarty_tpl->tpl_vars['_theme_config_rightbar']->value), null, 0);?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'] = array();?><?php  $_smarty_tpl->tpl_vars['section'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['section']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['_theme_config_rightbar']->value; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['section']->key => $_smarty_tpl->tpl_vars['section']->value){
$_smarty_tpl->tpl_vars['section']->_loop = true;
?><?php $_smarty_tpl->tpl_vars['section'] = new Smarty_variable(trim($_smarty_tpl->tpl_vars['section']->value), null, 0);?><?php if ($_smarty_tpl->tpl_vars['section']->value=="viewed"){?><?php $_smarty_tpl->tpl_vars['_viewed_pids'] = new Smarty_variable(waRequest::cookie('balance_viewed'), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_viewed_pids']->value)){?><?php $_smarty_tpl->tpl_vars['_viewed_products'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->products("id/".((string)$_smarty_tpl->tpl_vars['_viewed_pids']->value),5), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_viewed_products']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="filters"){?><?php if (isset($_smarty_tpl->tpl_vars['filters']->value)&&!empty($_smarty_tpl->tpl_vars['filters']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="tags"){?><?php $_smarty_tpl->tpl_vars['_shop_tags'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->tags(15), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_shop_tags']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="categories"){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['categories_links'] = $_smarty_tpl->tpl_vars['wa']->value->shop->categories(0,3,true,true);?><?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['categories_links'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="menu"){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'] = $_smarty_tpl->tpl_vars['wa']->value->shop->categories(0,3,true,true);?><?php if (!empty($_smarty_tpl->tpl_vars['_theme_config']->value['mainmenu_links'])){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="productbrands"){?><?php if (method_exists("shopProductbrandsPlugin","getBrands")){?><?php $_smarty_tpl->tpl_vars['_shop_brands'] = new Smarty_variable(shopProductbrandsPlugin::getBrands(), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['_shop_brands']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="last-posts"){?><?php if ($_smarty_tpl->tpl_vars['wa']->value->blog){?><?php $_smarty_tpl->tpl_vars['sidebar_posts'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->blog->posts(null,2), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['sidebar_posts']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="products"){?><?php if ($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_products_limit']>0){?><?php $_smarty_tpl->tpl_vars['limit'] = new Smarty_variable($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_products_limit'], null, 0);?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['limit'] = new Smarty_variable(4, null, 0);?><?php }?><?php $_smarty_tpl->tpl_vars['sidebar_products'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->shop->productSet($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_products_set'],$_smarty_tpl->tpl_vars['limit']->value), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['sidebar_products']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="faq"){?><?php $_smarty_tpl->tpl_vars['_faq'] = new Smarty_variable(array(), null, 0);?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_1_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_1_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_1_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_2_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_2_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_2_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_3_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_3_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_3_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_4_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_4_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_4_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_5_question'])){?><?php $_smarty_tpl->createLocalArrayVariable('_faq', null, 0);
$_smarty_tpl->tpl_vars['_faq']->value[] = array('question'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_5_question'],'answer'=>$_smarty_tpl->tpl_vars['theme_settings']->value['shop_sidebars_sections_faq_5_answer']);?><?php }?><?php if (!empty($_smarty_tpl->tpl_vars['_faq']->value)){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }?><?php }elseif($_smarty_tpl->tpl_vars['section']->value=="about"){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'section','value'=>$_smarty_tpl->tpl_vars['section']->value);?><?php }elseif(substr($_smarty_tpl->tpl_vars['section']->value,0,6)=="block="){?><?php $_smarty_tpl->tpl_vars['sidebar_block'] = new Smarty_variable($_smarty_tpl->tpl_vars['wa']->value->block(smarty_modifier_replace($_smarty_tpl->tpl_vars['section']->value,"block=",'')), null, 0);?><?php if ($_smarty_tpl->tpl_vars['sidebar_block']->value){?><?php $_smarty_tpl->createLocalArrayVariable('_theme_config', null, 0);
$_smarty_tpl->tpl_vars['_theme_config']->value['rightbar'][] = array('type'=>'block','value'=>$_smarty_tpl->tpl_vars['sidebar_block']->value);?><?php }?><?php }?><?php } ?><?php $_smarty_tpl->tpl_vars['_theme_config_bars'] = new Smarty_variable(array_merge($_smarty_tpl->tpl_vars['_theme_config_leftbar']->value,$_smarty_tpl->tpl_vars['_theme_config_rightbar']->value), null, 0);?><?php }} ?><?php /* Smarty version Smarty-3.1.14, created on 2020-12-21 08:37:59
         compiled from "/var/www/u1240732/data/www/mirschetok.ru/wa-data/public/shop/themes/balance/category.subcategories.html" */ ?>
<?php if ($_valid && !is_callable('content_5fe034b767e556_83516902')) {function content_5fe034b767e556_83516902($_smarty_tpl) {?><?php $_smarty_tpl->tpl_vars['_balance_recalculate_products'] = new Smarty_variable(true, null, 0);?><?php if (isset($_smarty_tpl->tpl_vars['category']->value['params']['subcategories_view'])&&in_array($_smarty_tpl->tpl_vars['category']->value['params']['subcategories_view'],array('blocks','buttons','list','miniblocks','miniblocks-slider'))){?><?php $_smarty_tpl->tpl_vars['_subcategories_view'] = new Smarty_variable($_smarty_tpl->tpl_vars['category']->value['params']['subcategories_view'], null, 0);?><?php }else{ ?><?php $_smarty_tpl->tpl_vars['_subcategories_view'] = new Smarty_variable($_smarty_tpl->tpl_vars['theme_settings']->value['products_subcategories_view'], null, 0);?><?php }?><?php if (!isset($_smarty_tpl->tpl_vars['_subcategories_view']->value)||$_smarty_tpl->tpl_vars['_subcategories_view']->value=="blocks"){?><div class="catalog-pg__subcat catalog-pg__subcat_nobd"><div class="layout-center"><div class="subcat-wrapper subcat-wrapper_pic"><?php  $_smarty_tpl->tpl_vars['subcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subcat']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['category']->value['subcategories']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subcat']->key => $_smarty_tpl->tpl_vars['subcat']->value){
$_smarty_tpl->tpl_vars['subcat']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_balance_recalculate_products']->value){?><?php $_smarty_tpl->createLocalArrayVariable('subcat', null, 0);
$_smarty_tpl->tpl_vars['subcat']->value['count'] = $_smarty_tpl->tpl_vars['wa']->value->shop->productsCount("category/".((string)$_smarty_tpl->tpl_vars['subcat']->value['id']));?><?php }?><div class="subcat-wrapper__item sub-cat-nobd"><a href="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['url'];?>
" class="sub-cat sub-cat_nobd sub-cat_primary sub-cat_cat"><?php if (!empty($_smarty_tpl->tpl_vars['subcat']->value['params']['image'])){?><div class="sub-cat__image"><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['params']['image'];?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['subcat']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"></div><?php }else{ ?><?php if (method_exists("shopWmimageincatPlugin","getCategoryImage")){?><?php if (shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'image')){?><div class="sub-cat__image"><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'image');?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['subcat']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"></div><?php }?><?php }?><?php }?><div class="sub-cat__qty"><div class="sub-cat-qty"><?php echo (($tmp = @$_smarty_tpl->tpl_vars['subcat']->value['count'])===null||$tmp==='' ? 0 : $tmp);?>
</div></div><div class="sub-cat__title"><?php echo $_smarty_tpl->tpl_vars['subcat']->value['name'];?>
</div></a></div><?php } ?><a class="subcat-wrapper__mob-qty-toggle" href="#" data-show="показать еще" data-hide="свернуть"><span>показать еще</span><svg class="icon" width="8" height="5"><use xlink:href="#icon-down-btn"></use></svg></a></div></div></div><?php }elseif($_smarty_tpl->tpl_vars['_subcategories_view']->value=="buttons"){?><div class="catalog-pg__subcat"><div class="subcat-wrapper subcat-wrapper_nopic"><?php  $_smarty_tpl->tpl_vars['subcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subcat']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['category']->value['subcategories']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subcat']->key => $_smarty_tpl->tpl_vars['subcat']->value){
$_smarty_tpl->tpl_vars['subcat']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_balance_recalculate_products']->value){?><?php $_smarty_tpl->createLocalArrayVariable('subcat', null, 0);
$_smarty_tpl->tpl_vars['subcat']->value['count'] = $_smarty_tpl->tpl_vars['wa']->value->shop->productsCount("category/".((string)$_smarty_tpl->tpl_vars['subcat']->value['id']));?><?php }?><div class="subcat-wrapper__item subcat-wrapper__item_mini"><a class="subcat-mini" href="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['url'];?>
"><span class="subcat-mini__text"><?php echo $_smarty_tpl->tpl_vars['subcat']->value['name'];?>
</span><span class="subcat-mini__qty"><?php echo (($tmp = @$_smarty_tpl->tpl_vars['subcat']->value['count'])===null||$tmp==='' ? 0 : $tmp);?>
</span></a></div><?php } ?><a class="subcat-wrapper__mob-qty-toggle" href="#" data-show="показать еще" data-hide="свернуть"><span>показать еще</span><svg class="icon" width="8" height="5"><use xlink:href="#icon-down-btn"></use></svg></a></div></div><?php }elseif($_smarty_tpl->tpl_vars['_subcategories_view']->value=="list"){?><div class="catalog-pg__subcat catalog-pg__subcat_nobd"><div class="layout-center"><div class="subcat-wrapper subcat-wrapper_text"><?php  $_smarty_tpl->tpl_vars['subcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subcat']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['category']->value['subcategories']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subcat']->key => $_smarty_tpl->tpl_vars['subcat']->value){
$_smarty_tpl->tpl_vars['subcat']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_balance_recalculate_products']->value){?><?php $_smarty_tpl->createLocalArrayVariable('subcat', null, 0);
$_smarty_tpl->tpl_vars['subcat']->value['count'] = $_smarty_tpl->tpl_vars['wa']->value->shop->productsCount("category/".((string)$_smarty_tpl->tpl_vars['subcat']->value['id']));?><?php }?><div class="subcat-wrapper__item subcat-wrapper__item_text"><a class="subcat-text" href="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['url'];?>
"><span class="subcat-text__text"><?php echo $_smarty_tpl->tpl_vars['subcat']->value['name'];?>
</span><span>(<?php echo (($tmp = @$_smarty_tpl->tpl_vars['subcat']->value['count'])===null||$tmp==='' ? 0 : $tmp);?>
)</span></a></div><?php } ?></div></div></div><?php }elseif($_smarty_tpl->tpl_vars['_subcategories_view']->value=="miniblocks"){?><div class="catalog-pg__subcat"><div class="layout-center"><div class="subcat-wrapper subcat-wrapper_pic"><?php  $_smarty_tpl->tpl_vars['subcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subcat']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['category']->value['subcategories']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subcat']->key => $_smarty_tpl->tpl_vars['subcat']->value){
$_smarty_tpl->tpl_vars['subcat']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_balance_recalculate_products']->value){?><?php $_smarty_tpl->createLocalArrayVariable('subcat', null, 0);
$_smarty_tpl->tpl_vars['subcat']->value['count'] = $_smarty_tpl->tpl_vars['wa']->value->shop->productsCount("category/".((string)$_smarty_tpl->tpl_vars['subcat']->value['id']));?><?php }?><div class="subcat-wrapper__item subcat-wrapper__item_sec sub-cat-bd"><a href="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['url'];?>
" class="sub-cat sub-cat_cat sub-cat_bd sub-cat_sec"><?php if (!empty($_smarty_tpl->tpl_vars['subcat']->value['params']['image'])){?><div class="sub-cat__image"><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['params']['image'];?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['subcat']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"></div><?php }else{ ?><?php if (method_exists("shopWmimageincatPlugin","getCategoryImage")){?><?php if (shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'image')){?><div class="sub-cat__image"><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'image');?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['subcat']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"></div><?php }?><?php }?><?php }?><div class="sub-cat__qty"><div class="sub-cat-qty"><?php echo (($tmp = @$_smarty_tpl->tpl_vars['subcat']->value['count'])===null||$tmp==='' ? 0 : $tmp);?>
</div></div><div class="sub-cat__title"><?php echo $_smarty_tpl->tpl_vars['subcat']->value['name'];?>
</div><div class="sub-cat__arrow"><svg class="icon" width="6" height="11"><use xlink:href="#arrow-vert-menu"></use></svg></div></a></div><?php } ?><a class="subcat-wrapper__mob-qty-toggle" href="#" data-show="показать еще" data-hide="свернуть"><span>показать еще</span><svg class="icon" width="8" height="5"><use xlink:href="#icon-down-btn"></use></svg></a></div></div></div><?php }elseif($_smarty_tpl->tpl_vars['_subcategories_view']->value=="miniblocks-slider"){?><div class="catalog-pg__subcat"><div class="layout-center"><div class="subcat-slider"><div class="subcat-slider__arrows"><button class="slider-ar slider-ar_square pos-rel default-btn"><svg class="icon cent-icon" width="7" height="11"><use xlink:href="#arrow-left-small"></use></svg></button><button class="slider-ar slider-ar_square pos-rel default-btn"><svg class="icon cent-icon" width="7" height="11"><use xlink:href="#arrow-right-small"></use></svg></button></div><div class="subcat-slider__container swiper-container"><div class="subcat-wrapper subcat-wrapper_pic swiper-wrapper"><?php  $_smarty_tpl->tpl_vars['subcat'] = new Smarty_Variable; $_smarty_tpl->tpl_vars['subcat']->_loop = false;
 $_from = $_smarty_tpl->tpl_vars['category']->value['subcategories']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array');}
foreach ($_from as $_smarty_tpl->tpl_vars['subcat']->key => $_smarty_tpl->tpl_vars['subcat']->value){
$_smarty_tpl->tpl_vars['subcat']->_loop = true;
?><?php if ($_smarty_tpl->tpl_vars['_balance_recalculate_products']->value){?><?php $_smarty_tpl->createLocalArrayVariable('subcat', null, 0);
$_smarty_tpl->tpl_vars['subcat']->value['count'] = $_smarty_tpl->tpl_vars['wa']->value->shop->productsCount("category/".((string)$_smarty_tpl->tpl_vars['subcat']->value['id']));?><?php }?><div class="subcat-wrapper__item subcat-wrapper__item_sec swiper-slide"><a href="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['url'];?>
" class="sub-cat sub-cat_cat sub-cat_bd sub-cat_cat sub-cat_sec"><?php if (!empty($_smarty_tpl->tpl_vars['subcat']->value['params']['image'])){?><div class="sub-cat__image"><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo $_smarty_tpl->tpl_vars['subcat']->value['params']['image'];?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['subcat']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"></div><?php }else{ ?><?php if (method_exists("shopWmimageincatPlugin","getCategoryImage")){?><?php if (shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'image')){?><div class="sub-cat__image"><img src="data:image/gif;base64,R0lGODlh6gDqAIAAAP///wAAACH5BAEAAAEALAAAAADqAOoAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vv8PGCg4SFhoeIiYqLjI2Oj4CBkpOUlZaXmJmam5ydnp+QkaKjpKWmp6ipqqusra6voKGys7S1tre4ubq7vL2+v7CxwsPExcbHyMnKy8zNzs/AwdLT1NXW19jZ2tvc3d7f0NHi4+Tl5ufo6err7O3u7+Dh8vP09fb3+Pn6+/z9/v/w8woMCBBAsaPIgwocKFDBs6fAgxosSJFCtavIgxo8Y9jRw7evwIMqTIkSRLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOo1UAAA7" data-src="<?php echo shopWmimageincatPlugin::getCategoryImage($_smarty_tpl->tpl_vars['subcat']->value['id'],'image');?>
" class="lazy-img" alt="<?php echo htmlspecialchars($_smarty_tpl->tpl_vars['subcat']->value['name'], ENT_QUOTES, 'UTF-8', true);?>
"></div><?php }?><?php }?><?php }?><div class="sub-cat__qty"><div class="sub-cat-qty"><?php echo (($tmp = @$_smarty_tpl->tpl_vars['subcat']->value['count'])===null||$tmp==='' ? 0 : $tmp);?>
</div></div><div class="sub-cat__title"><?php echo $_smarty_tpl->tpl_vars['subcat']->value['name'];?>
</div></a></div><?php } ?><a class="subcat-wrapper__mob-qty-toggle" href="#" data-show="показать еще" data-hide="свернуть"><span>показать еще</span><svg class="icon" width="8" height="5"><use xlink:href="#icon-down-btn"></use></svg></a></div></div></div></div></div><?php }?><?php }} ?>