<?php
return array (
  'mirschetok.ru' => 
  array (
    0 => 
    array (
      'url' => 'blog/*',
      'app' => 'blog',
      'locale' => 'ru_RU',
      'blog_url_type' => 1,
      'theme' => 'balance',
      'theme_mobile' => 'balance',
    ),
    1 => 
    array (
      'url' => 'contacts/*',
      'app' => 'contacts',
      'private' => '1',
      'ssl_all' => '1',
    ),
    2 => 
    array (
      'url' => 'site/*',
      'app' => 'site',
      'theme' => 'balance',
      'theme_mobile' => 'balance',
      'locale' => 'ru_RU',
      'private' => '1',
      'ssl_all' => '1',
    ),
    3 => 
    array (
      'url' => '*',
      'app' => 'shop',
      'theme' => 'balance',
      'theme_mobile' => 'balance',
      'checkout_version' => '2',
      'locale' => 'ru_RU',
      'ssl_all' => '1',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'og_title' => '',
      'og_image' => '',
      'og_video' => '',
      'og_description' => '',
      'og_type' => '',
      'og_url' => '',
      'url_type' => '1',
      'products_per_page' => '',
      'type_id' => '0',
      'currency' => 'RUB',
      'public_stocks' => '0',
      'drop_out_of_stock' => '0',
      'payment_id' => '0',
      'shipping_id' => '0',
      'ssl' => '1',
      'checkout_storefront_id' => 'a8d2f0bbb9742388db84708dd578016d',
    ),
  ),
  'dev.mirschetok.ru' => 
  array (
    3 => 
    array (
      'url' => 'blog/*',
      'app' => 'blog',
      'theme' => 'balance',
      'theme_mobile' => 'balance',
      'locale' => 'ru_RU',
      'private' => '1',
      'ssl_all' => '1',
      'blog_url_type' => '1',
      'post_url_type' => '0',
      'title_type' => 'blog_post',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'rss_title' => '',
    ),
    2 => 
    array (
      'url' => 'contacts/*',
      'app' => 'contacts',
      'private' => '1',
      'ssl_all' => '1',
    ),
    'site' => 
    array (
      'url' => 'site/*',
      'app' => 'site',
      'theme' => 'wiper_desc',
      'theme_mobile' => 'wiper_mobi',
      'locale' => 'ru_RU',
      'private' => '1',
      'ssl_all' => '1',
    ),
    1 => 
    array (
      'url' => '*',
      'app' => 'shop',
      'theme' => 'wiper_desc',
      'theme_mobile' => 'wiper_mobi',
      'checkout_version' => '2',
      'locale' => 'ru_RU',
      'ssl_all' => '1',
      'title' => '',
      'meta_keywords' => '',
      'meta_description' => '',
      'og_title' => '',
      'og_image' => '',
      'og_video' => '',
      'og_description' => '',
      'og_type' => '',
      'og_url' => '',
      'url_type' => '0',
      'products_per_page' => '',
      'type_id' => '0',
      'currency' => 'RUB',
      'public_stocks' => '0',
      'drop_out_of_stock' => '0',
      'payment_id' => '0',
      'shipping_id' => '0',
      'ssl' => '1',
      'checkout_storefront_id' => 'c2c3014ded61272503e7bbf76c38a356',
    ),
  ),
);
