<?php
return array(
    'shop_sdekint_calc_rules' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'status' => array('int', 1, 'null' => 0, 'default' => '1'),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'methods' => array('text'),
        'courier' => array('text'),
        'point' => array('text'),
        'conditions' => array('text'),
        'condition_join_type' => array('varchar', 3, 'null' => 0, 'default' => 'and'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_sdekint_calc_rules_sort_index' => 'sort',
        ),
    ),
    'shop_sdekint_cities' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'country_iso3' => array('char', 3, 'null' => 0),
        'region_code' => array('varchar', 8),
        'name' => array('varchar', 255, 'null' => 0),
        'area' => array('varchar', 255),
        'sdek_id' => array('int', 11, 'null' => 0),
        'is_center' => array('int', 11, 'null' => 0, 'default' => '0'),
        'pod_max' => array('decimal', "15,2"),
        ':keys' => array(
            'PRIMARY' => 'id',
            'name_index' => 'name',
            'country_iso3_region_code_index' => array('country_iso3', 'region_code'),
            'sdek_id_index' => 'sdek_id',
            'pod_max_index' => 'pod_max',
        ),
    ),
    'shop_sdekint_courier_calls' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'code' => array('varchar', 50),
        'call_date' => array('date', 'null' => 0),
        'time_beg' => array('time', 'null' => 0),
        'time_end' => array('time', 'null' => 0),
        'send_phone' => array('varchar', 60, 'null' => 0),
        'send_name' => array('varchar', 255, 'null' => 0),
        'weight' => array('int', 11),
        'comment' => array('varchar', 255, 'null' => 0),
        'city_code' => array('int', 11, 'null' => 0),
        'address_street' => array('varchar', 50, 'null' => 0),
        'address_house' => array('varchar', 30, 'null' => 0),
        'address_flat' => array('varchar', 10, 'null' => 0),
        'sent' => array('datetime', 'null' => 0),
        'dispatch_number' => array('varchar', 50),
        'order_no' => array('varchar', 60),
        'number_ttn' => array('varchar', 60),
        ':keys' => array(
            'PRIMARY' => 'id',
            'code_index' => 'code',
            'call_date_index' => 'call_date',
            'time_beg_index' => 'time_beg',
            'order_no_index' => 'order_no',
            'ttn_index' => 'number_ttn',
        ),
    ),
    'shop_sdekint_order_actions' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_state' => array('varchar', 255, 'null' => 0),
        'sdek_state' => array('int', 11, 'null' => 0),
        'wf_action' => array('varchar', 255, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_sdek' => array('shop_state', 'sdek_state', 'unique' => 1),
        ),
    ),
    'shop_sdekint_pvz' => array(
        'code' => array('varchar', 10, 'null' => 0),
        'name' => array('varchar', 50, 'null' => 0),
        'country_name_sdek' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'country_code_sdek' => array('varchar', 10, 'null' => 0, 'default' => ''),
        'region_code_sdek' => array('varchar', 10, 'null' => 0, 'default' => ''),
        'city_code' => array('int', 11, 'null' => 0),
        'city' => array('varchar', 50, 'null' => 0),
        'work_time' => array('varchar', 100, 'null' => 0),
        'address' => array('varchar', 255, 'null' => 0),
        'full_address' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'phone' => array('varchar', 100, 'null' => 0),
        'note' => array('varchar', 255, 'null' => 0),
        'coord_x' => array('decimal', "10,6", 'null' => 0),
        'coord_y' => array('decimal', "10,6", 'null' => 0),
        'min_weight' => array('int', 11),
        'max_weight' => array('int', 11),
        'owner' => array('varchar', 64),
        'point_type' => array('varchar', 32),
        'dressing_room' => array('int', 1, 'null' => 0, 'default' => '0'),
        'have_cashless' => array('int', 1, 'null' => 0, 'default' => '0'),
        'allowed_cod' => array('int', 1, 'null' => 0, 'default' => '0'),
        'nearest_station' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'metro' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'site' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'address_comment' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'raw_data' => array('longtext'),
        'region_name_sdek' => array('varchar', 50, 'null' => 0, 'default' => ''),
        ':keys' => array(
            'PRIMARY' => 'code',
            'city_code_index' => 'city_code',
            'city_index' => 'city',
            'owner' => 'owner',
            'point_type' => 'point_type',
        ),
    ),
    'shop_sdekint_widget_settings' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 150),
        'settings' => array('text', 'null' => 0),
        'type' => array('varchar', 30, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
);
