<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Webit\\Util\\EvalMath\\' => array($vendorDir . '/webit/eval-math/src'),
    'Syrnik\\' => array($vendorDir . '/syrnik/html/src', $vendorDir . '/syrnik/wa-logger/src'),
    'SergeR\\Webasyst\\Shipping\\Packages\\' => array($vendorDir . '/serger/webasyst-shipping-package/src'),
    'SergeR\\Webasyst\\CdekSDK\\' => array($vendorDir . '/CdekSDK/src'),
    'SergeR\\CakeUtility\\' => array($vendorDir . '/serger/cake-utility/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'PhpUnitsOfMeasure\\' => array($vendorDir . '/php-units-of-measure/php-units-of-measure/source'),
);
