<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf2ebd81259cfd7423e4dd24a2d216267
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Webit\\Util\\EvalMath\\' => 20,
        ),
        'S' => 
        array (
            'Syrnik\\' => 7,
            'SergeR\\Webasyst\\Shipping\\Packages\\' => 34,
            'SergeR\\Webasyst\\CdekSDK\\' => 24,
            'SergeR\\CakeUtility\\' => 19,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'PhpUnitsOfMeasure\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Webit\\Util\\EvalMath\\' => 
        array (
            0 => __DIR__ . '/..' . '/webit/eval-math/src',
        ),
        'Syrnik\\' => 
        array (
            0 => __DIR__ . '/..' . '/syrnik/html/src',
            1 => __DIR__ . '/..' . '/syrnik/wa-logger/src',
        ),
        'SergeR\\Webasyst\\Shipping\\Packages\\' => 
        array (
            0 => __DIR__ . '/..' . '/serger/webasyst-shipping-package/src',
        ),
        'SergeR\\Webasyst\\CdekSDK\\' => 
        array (
            0 => __DIR__ . '/..' . '/CdekSDK/src',
        ),
        'SergeR\\CakeUtility\\' => 
        array (
            0 => __DIR__ . '/..' . '/serger/cake-utility/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'PhpUnitsOfMeasure\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-units-of-measure/php-units-of-measure/source',
        ),
    );

    public static $prefixesPsr0 = array (
        'D' => 
        array (
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf2ebd81259cfd7423e4dd24a2d216267::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf2ebd81259cfd7423e4dd24a2d216267::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitf2ebd81259cfd7423e4dd24a2d216267::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
